import { Injectable } from '@nestjs/common';
import { AuthUser } from '../common/types/auth-user';
import { DatabaseService } from '../database/database.service';

type LotRow = { lot_id: string; tenant_id: string; article_id: string; article_code: string | null; commercial_name: string | null; supplier_id: string | null; supplier_name: string | null; lot_number: string; expiry_date: string; purchase_price: string; selling_price: string; currency_id: string | null; currency_code: string | null; currency_symbol: string | null; is_blocked: boolean; block_reason: string | null; created_at: Date };

@Injectable()
export class LotsRepository {
  constructor(private readonly db: DatabaseService) {}
  async findAll(user: AuthUser) { const r = await this.db.query<LotRow>(this.baseSql('WHERE l.tenant_id=$1 AND ($2::uuid IS NULL OR EXISTS (SELECT 1 FROM stocks st WHERE st.tenant_id=l.tenant_id AND st.lot_id=l.lot_id AND st.site_id=$2::uuid)) ORDER BY l.expiry_date ASC'), [user.tenantId, user.siteId ?? null]); return r.rows.map(this.toDto); }
  async findOne(user: AuthUser, id: string) { const r = await this.db.query<LotRow>(this.baseSql('WHERE l.tenant_id=$1 AND l.lot_id=$2 AND ($3::uuid IS NULL OR EXISTS (SELECT 1 FROM stocks st WHERE st.tenant_id=l.tenant_id AND st.lot_id=l.lot_id AND st.site_id=$3::uuid)) LIMIT 1'), [user.tenantId, id, user.siteId ?? null]); return r.rows[0] ? this.toDto(r.rows[0]) : null; }
  async block(user: AuthUser, id: string, reason?: string) { await this.db.query(`UPDATE lots l SET is_blocked=true, block_reason=$3 WHERE tenant_id=$1 AND lot_id=$2 AND ($4::uuid IS NULL OR EXISTS (SELECT 1 FROM stocks st WHERE st.tenant_id=l.tenant_id AND st.lot_id=l.lot_id AND st.site_id=$4::uuid))`, [user.tenantId, id, reason ?? 'Blocked', user.siteId ?? null]); return this.findOne(user, id); }
  async unblock(user: AuthUser, id: string) { await this.db.query(`UPDATE lots l SET is_blocked=false, block_reason=NULL WHERE tenant_id=$1 AND lot_id=$2 AND ($3::uuid IS NULL OR EXISTS (SELECT 1 FROM stocks st WHERE st.tenant_id=l.tenant_id AND st.lot_id=l.lot_id AND st.site_id=$3::uuid))`, [user.tenantId, id, user.siteId ?? null]); return this.findOne(user, id); }
  private baseSql(where: string) { return `SELECT l.lot_id, l.tenant_id, l.article_id, a.article_code, a.commercial_name, l.supplier_id, s.supplier_name, l.lot_number, l.expiry_date, l.purchase_price, l.selling_price, l.currency_id, c.currency_code, CASE WHEN c.currency_code='CDF' THEN 'FC' WHEN c.currency_code='USD' THEN '$' ELSE c.currency_code END AS currency_symbol, l.is_blocked, l.block_reason, l.created_at FROM lots l JOIN articles a ON a.article_id=l.article_id AND a.tenant_id=l.tenant_id LEFT JOIN suppliers s ON s.supplier_id=l.supplier_id AND s.tenant_id=l.tenant_id LEFT JOIN currencies c ON c.currency_id=l.currency_id ${where}`; }
  private toDto(row: LotRow) { return { lotId: row.lot_id, tenantId: row.tenant_id, articleId: row.article_id, articleCode: row.article_code, commercialName: row.commercial_name, supplierId: row.supplier_id, supplierName: row.supplier_name, lotNumber: row.lot_number, expiryDate: row.expiry_date, purchasePrice: Number(row.purchase_price), sellingPrice: Number(row.selling_price), currencyId: row.currency_id, currencyCode: row.currency_code, currencySymbol: row.currency_symbol, isBlocked: row.is_blocked, blockReason: row.block_reason, createdAt: row.created_at }; }
}
